import "./globals.css";
import { Major_Mono_Display, Philosopher, Quicksand } from "next/font/google";

const quicksand = Quicksand({
	subsets: ["latin"],
	variable: "--font-base",
});

const majorMonoDisplay = Major_Mono_Display({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-nufogy-typo",
});

const philosopher = Philosopher({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-headings",
});
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${quicksand.variable} ${majorMonoDisplay.variable} ${philosopher.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
